version: "3.7"

services:

    api-server:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/usr/src/app
        ports: 
            - 5001:5000
        environment: 
            - FLASK_APP=project/__init__.py
            - FLASK_ENV=development
            - APP_SETTINGS=development
            - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/blogs
            - TEST_DATABASE_URL=postgresql://postgres:postgres@api-db:5432/blogs_testdb
            - MAIL_USERNAME=hadijahzrecipes@gmail.com
            - MAIL_PASSWORD=devhadijah315
        depends_on: 
            - api-db
    
    api-db:
        build: 
            context: ./api/blogs/db
            dockerfile: Dockerfile
        expose: 
            - 5432
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres